name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: hadolint/hadolint-action@v3.1.0
      with:
        dockerfile: Dockerfile
    name: "Dive CI"
  dive:
    runs-on: ubuntu-latest
    name: Analyze image efficiency
    steps:
    - name: Maximize build space
      uses: easimon/maximize-build-space@v10
      with:
        root-reserve-mb: 1024
        swap-size-mb: 0
        remove-dotnet: true
        remove-android: true
        remove-haskell: true
        remove-codeql: true
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build image
        run: docker build -t sample:latest .
      - name: Dive
        uses: yuichielectric/dive-action@0.0.4
        with:
          image: "sample:latest"
          config-file: ${{ github.workspace }}/.dive-ci.yml
          github-token: ${{ secrets.GITHUB_TOKEN }}
